FROM python:3.9-slim
WORKDIR /app
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
COPY requirements-daemon.txt .
RUN pip install --no-cache-dir -r requirements-daemon.txt
COPY avalanche_daemon_opt.py .
CMD ["python", "avalanche_daemon_opt.py"]
