# docker-compose.octo.yml
version: '3.8'

services:
  octo-supervisor:
    build:
      context: .
      dockerfile: Dockerfile.octo
    container_name: octo_supervisor
    ports:
      - "5003:5003"
    environment:
      - KAFKA_BROKER=kafka:9092
      - OCTO_GROUP=octo-supervisor
      - CONFIDENCE_THRESHOLD=0.82
    volumes:
      - ./secrets:/app/secrets
      - ./logs:/app/logs
    depends_on:
      - kafka
    networks:
      - arachne_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  arachne_net:
    external: true
